// The nspasteboard.org markers a writer puts beside what it copies.

/// What a copy's writer says about it, by the nspasteboard.org convention. See Docs/clipboard-secrets.md.
public struct PasteboardMarkers: OptionSet, Sendable, Hashable {
    public let rawValue: Int

    public init(rawValue: Int) { self.rawValue = rawValue }

    /// A password or similar, which may be kept but must not be shown.
    public static let concealed = PasteboardMarkers(rawValue: 1 << 0)
    /// A copy made to move data somewhere, never meant for a history.
    public static let transient = PasteboardMarkers(rawValue: 1 << 1)
    /// Contents written by software rather than copied by a person.
    public static let autoGenerated = PasteboardMarkers(rawValue: 1 << 2)

    /// The markers named among a clipboard's type identifiers; every other type is ignored.
    public init(types: [String]) {
        self = types.reduce(into: []) { markers, type in
            switch type {
            case Self.convention + "ConcealedType": markers.insert(.concealed)
            case Self.convention + "TransientType": markers.insert(.transient)
            case Self.convention + "AutoGeneratedType": markers.insert(.autoGenerated)
            default: break
            }
        }
    }

    /// The prefix of every type the convention defines, which names a format and not an app.
    private static let convention = "org.nspasteboard."

    /// Whether a history may record the copy at all; concealed is recorded and hidden.
    public var allowsRecording: Bool { isDisjoint(with: [.transient, .autoGenerated]) }
}
